steps:
    - id: 'build image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}', '.']

    - id: 'push image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}']

substitutions:
    _PROJECT_ID: cm-cluster-coordinadora-dev
    _SERVICE_NAME: api-samples

images:
    - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
